CREATE TABLE "VBJ{receiving_year}VERS_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "GEBJAHR" NUMBER(4) NOT NULL,
    "PLZ" VARCHAR2(5),
    "VITALSTATUS" NUMBER(1) NOT NULL,
    "STERBEDAT" NUMBER(8),
    "KASSENIK" NUMBER(9) NOT NULL,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}VERSQ_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "VERSQ" NUMBER(5) NOT NULL,
    "GESCHLECHT" NUMBER(1) NOT NULL,
    "VERSTAGE" NUMBER NOT NULL,
    "VERSTAGEAUSL" NUMBER NOT NULL,
    "VERSSTATUS" NUMBER(5) NOT NULL,
    "VERSTAGEKG" NUMBER NOT NULL,
    "VERSTAGEKOSTERSTWAHLT" NUMBER NOT NULL,
    "KASSENIK" NUMBER(9) NOT NULL,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}VERSQDMP_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "VERSQ" NUMBER(5) NOT NULL,
    "DMPPROG" VARCHAR2(2) NOT NULL,
    "DMPTAGE" NUMBER NOT NULL,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}AMBFALL_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "ABRQ" NUMBER(5) NOT NULL,
    "FALLIDAMB" VARCHAR2(11) NOT NULL,
    "SVNR" VARCHAR2(25),
    "SVTYP" NUMBER(1),
    "BSNRPSEUDO" NUMBER(12),
    "BSNRKV" NUMBER(2),
    "BSNRUEBPSEUDO" NUMBER(12),
    "BSNRUEBKV" NUMBER(2),
    "LANRUEBPSEUDO" NUMBER(12),
    "LANRUEBFG" NUMBER(2),
    "LANRUEBPRUEF" VARCHAR2(1),
    "INANSPRARTAMB" VARCHAR2(1) NOT NULL,
    "UNFALL" NUMBER(1) NOT NULL,
    "BEHANDARTAMB" NUMBER(1),
    "ENTBINDUNGSDAT" NUMBER(8),
    "PUNKTZAHL" REAL,
    "FALLKOAMB" REAL,
    "DIALYSESACHKO" REAL,
    "BEGINNDATAMB" NUMBER(8),
    "ENDEDATAMB" NUMBER(8),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}AMBDIAG_{schema}" (
    "FALLIDAMB" VARCHAR2(11) NOT NULL,
    "ICDAMB" VARCHAR2(12) NOT NULL,
    "DIAGSICH" VARCHAR2(1),
    "DIAGLOKAL" VARCHAR2(1),
    "DIAGDAT" NUMBER(8),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}AMBLEIST_{schema}" (
    "FALLIDAMB" VARCHAR2(11) NOT NULL,
    "NBSNRPSEUDO" NUMBER(12),
    "NBSNRKV" NUMBER(2),
    "LANRPSEUDO" NUMBER(12),
    "LANRFG" NUMBER(2),
    "LANRPRUEF" VARCHAR2(1),
    "GONR" VARCHAR2(25),
    "GONRDAT" NUMBER(8) NOT NULL,
    "MULTIPLIKATOR" VARCHAR2(80),
    "ABRBEGR" VARCHAR2(200),
    "SACHKOBEZ" VARCHAR2(200),
    "AMBLEISTZEIT" VARCHAR2(4),
    "TSVGART" NUMBER(12),
    "TSVGDAT" VARCHAR2(10),
    "TSVGARZT" VARCHAR2(20),
    "TSVGBSNRPSEUDO" NUMBER(12),
    "TSVGBSNRKV" NUMBER(2),
    "ZWEITMEIN" VARCHAR2(8),
    "GONRBEWERT" NUMBER(7,2),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}AMBOPS_{schema}" (
    "FALLIDAMB" VARCHAR2(11) NOT NULL,
    "OPS" VARCHAR2(12) NOT NULL,
    "OPSLOKAL" VARCHAR2(1),
    "OPSDAT" NUMBER(8),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}ZAHNFALL_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "LEISTQ" NUMBER(5),
    "FALLIDZAHN" VARCHAR2(11) NOT NULL,
    "ZANRPSEUDO" NUMBER(12),
    "ZANRABRPSEUDO" NUMBER(12),
    "ZAKZV" NUMBER(2),
    "BEHANDARTZAHN" VARCHAR2(2),
    "BEGINNDATZAHN" NUMBER(8),
    "ENDEDATZAHN" NUMBER(8),
    "FALLKOZAHN" NUMBER(12,2),
    "EIGENLABOR" NUMBER(12,2),
    "FREMDLABOR" NUMBER(12,2),
    "INANSPRARTZAHN" VARCHAR2(1),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}ZAHNLEIST_{schema}" (
    "FALLIDZAHN" VARCHAR2(11) NOT NULL,
    "LEISTDAT" NUMBER(8),
    "ZAHN" VARCHAR2(5),
    "GEBNR" VARCHAR2(25),
    "GEBPOS" VARCHAR2(5),
    "GEBNRZAHL" NUMBER,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}ZAHNBEF_{schema}" (
    "FALLIDZAHN" VARCHAR2(11) NOT NULL,
    "BEFNR" VARCHAR2(5),
    "ZAHN" VARCHAR2(95),
    "REFART" VARCHAR2(1),
    "BEFNRZAHL" NUMBER,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}REZ_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "REZNR" NUMBER(9) NOT NULL,
    "PZNREZ" VARCHAR2(10) NOT NULL,
    "VODAT" NUMBER(8) NOT NULL,
    "BSNRVOPSEUDO" NUMBER(12),
    "BSNRVOVB" NUMBER(2),
    "BSNRVOREGKNZ" NUMBER(2),
    "LENRVOPSEUDO" NUMBER(12),
    "LENRVOFG" NUMBER(2),
    "LENRVOPRUEF" VARCHAR2(1),
    "LENRVOPSEUDOARZTNR" VARCHAR2(1),
    "ABGABEDAT" NUMBER(8) NOT NULL,
    "BEGRUENDUNG" VARCHAR2(1),
    "VERTRAGSKZ" VARCHAR2(25),
    "APOPSEUDO" NUMBER(12) NOT NULL,
    "APOKLASS" NUMBER(2) NOT NULL,
    "APOREGKNZ" NUMBER(2) NOT NULL,
    "APOPRUEF" VARCHAR2(1),
    "APOSITZ" VARCHAR2(1),
    "APOTYP" VARCHAR2(1),
    "MENGE" NUMBER(6) NOT NULL,
    "NOCTU" VARCHAR2(1),
    "AUTIDEM" VARCHAR2(1) NOT NULL,
    "WIRKSTOFFVO" VARCHAR2(1),
    "AMBETRAG" REAL NOT NULL,
    "ABSCHLAEGE" REAL NOT NULL,
    "ZUZAHLKZ" VARCHAR2(1) NOT NULL,
    "ZUZAHLGES" REAL NOT NULL,
    "ZUZAHL" REAL,
    "MEHRKOSTEN" REAL,
    "EIGENBET" REAL,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}EZD_{schema}" (
    "REZNR" NUMBER(9) NOT NULL,
    "PZNEZD" VARCHAR2(8) NOT NULL,
    "ZAEHLER" NUMBER(2),
    "EINHEIT" VARCHAR(2),
    "FAKTOR" NUMBER(5) NOT NULL,
    "FAKTORKENNZEICHEN" VARCHAR2(2) NOT NULL,
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}KHFALL_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32) NOT NULL,
    "FALLIDKH" VARCHAR2(11) NOT NULL,
    "KHPSEUDO" NUMBER(12) NOT NULL,
    "KHKLASS" NUMBER(2) NOT NULL,
    "KHREGKZ" NUMBER(2) NOT NULL,
    "KHPRUEF" VARCHAR2(1),
    "AUFNDAT" VARCHAR2(8) NOT NULL,
    "AUFNGRUND" VARCHAR2(4),
    "ENTLASSGRUND" VARCHAR2(3),
    "AUFNFA" VARCHAR2(4),
    "EINWEISPSEUDO" NUMBER(12),
    "EINWEISFG" NUMBER(2),
    "EINWEISPRUEF" VARCHAR2(1),
    "VERANLASSKHPSEUDO" NUMBER(12),
    "VERANLASSKHKLASS" VARCHAR2(2),
    "VERANLASSKHREGKNZ" VARCHAR2(2),
    "VERANLASSKHPRUEF" VARCHAR2(1),
    "BEATSTD" VARCHAR2(4),
    "VERANLASSSTELLEPSEUDO" VARCHAR2(30),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}KHFA_{schema}" (
    "FALLIDKH" VARCHAR2(11) NOT NULL,
    "FA" VARCHAR2(4) NOT NULL,
    "ENTLASSDAT" VARCHAR2(8) NOT NULL,
    "ENTLASSZEIT" VARCHAR2(4),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}KHDIAG_{schema}" (
    "FALLIDKH" VARCHAR2(11) NOT NULL,
    "DIAGART" VARCHAR2(1) NOT NULL,
    "ICDKH" VARCHAR2(9) NOT NULL,
    "ICDLOKAL" VARCHAR2(1),
    "SEKICD" VARCHAR2(9),
    "SEKICDLOKAL" VARCHAR2(1),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}KHPROZ_{schema}" (
    "FALLIDKH" VARCHAR2(11) NOT NULL,
    "PROZ" VARCHAR2(11) NOT NULL,
    "PROZDAT" VARCHAR2(8),
    "PROZLOKAL" VARCHAR2(1),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}KHENTG_{schema}" (
    "FALLIDKH" VARCHAR2(11) NOT NULL,
    "ENTGART" VARCHAR2(8) NOT NULL,
    "ENTGBETRAG" NUMBER(12,2),
    "ABRVONDAT" VARCHAR2(8),
    "ABRBISDAT" VARCHAR2(8) NOT NULL,
    "ENTGZAHL" VARCHAR2(3),
    "TAGEOBE" VARCHAR2(3),
    "IMPFILE_ID" NUMBER NOT NULL
);

CREATE TABLE "VBJ{receiving_year}VS_{schema}" (
    "ARBNR" NUMBER(9,0),
    "PSID" RAW(32)
);
